// ==========================================
// 根布局组件
// 文件作用：定义整个应用的 HTML 结构和全局配置
// 关键点：Next.js App Router 的根布局，所有页面都会嵌套在这里
// ==========================================

// 导入 Next.js 的 Metadata 类型（用于 SEO 配置）
import type { Metadata } from "next";
// 导入 Google 字体：Geist 系列
// Geist: 现代的无衬线字体，适合界面文字
// Geist_Mono: 等宽字体，适合代码显示
import { Geist, Geist_Mono } from "next/font/google";
// 导入全局样式表
import "./globals.css";

// 配置 Geist Sans 字体
const geistSans = Geist({
  variable: "--font-geist-sans",  // CSS 变量名称
  subsets: ["latin"],             // 加载拉丁字符集（英文）
});

// 配置 Geist Mono 字体（等宽字体）
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",  // CSS 变量名称
  subsets: ["latin"],             // 加载拉丁字符集
});

// 导出元数据配置（用于 SEO）
export const metadata: Metadata = {
  title: "Create Next App",              // 页面标题
  description: "Generated by create next app",  // 页面描述
};

/**
 * 根布局组件
 * 作用：为所有页面提供统一的 HTML 结构
 * 
 * @param children - 子页面内容（自动传入）
 * @returns HTML 根元素
 * 
 * 关键点：
 * 1. 所有页面都会被包裹在这个布局中
 * 2. 使用 CSS 变量注入字体
 * 3. antialiased 类应用字体抗锯齿
 */
export default function RootLayout({
  children,  // 子页面内容
}: Readonly<{
  children: React.ReactNode;  // 只读属性，确保类型安全
}>) {
  return (
    // HTML 根元素，语言设置为英文
    <html lang="en">
      {/* 
        body 元素
        className 应用多个 CSS 类：
        - ${geistSans.variable}: 注入 Geist Sans 字体 CSS 变量
        - ${geistMono.variable}: 注入 Geist Mono 字体 CSS 变量
        - antialiased: Tailwind 类，启用字体抗锯齿
      */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 渲染子页面内容 */}
        {children}
      </body>
    </html>
  );
}
